source 'https://rubygems.org'


gem 'pry'
gem "rake"
gem 'rack-test'
gem 'rspec'
gem 'rack-cors', '~> 1.0.0'
gem "require_all"
gem "activerecord", "~> 5.2"
gem "sqlite3"
 gem 'rack', '1.6.13'
 gem 'shotgun', '0.9.0'



gem "sinatra"
gem "sinatra-activerecord"

